spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yjy91913/SpringcloudConfig
          searchPaths: respo
      label: master


server:
  port: 8888


